[metadata]
name = isynctab
version = 0.1.0
author = Al Zadid Sultan Bin Habib, Md Younus Ahamed, Prashnna Kumar Gyawali, Gianfranco Doretto, Donald A. Adjeroh
description = Learning Cross-Modal Feature Sequencing for Multimodal Data via Neural Synchrony
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/zadid6pretam/iSyncTab

project_urls =
    Paper = https://doi.org/10.1007/978-3-032-37035-8
    Conference = https://eccv.ecva.net
    Homepage = https://www.zadidhabib.com/isynctab.html
    Source = https://github.com/zadid6pretam/iSyncTab
    Issues = https://github.com/zadid6pretam/iSyncTab/issues

classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Operating System :: OS Independent
    Intended Audience :: Science/Research
    Topic :: Scientific/Engineering :: Artificial Intelligence
    Topic :: Scientific/Engineering :: Image Processing
    Topic :: Scientific/Engineering :: Information Analysis

[options]
packages = find:
python_requires = >=3.10
include_package_data = True

[options.packages.find]
include =
    isynctab
    isynctab.*
